[package]
name = "rustfmt-bin"
version = "0.4.0"
authors = ["Nicholas Cameron <ncameron@mozilla.com>", "The Rustfmt developers"]
description = "Tool to find and fix Rust formatting issues"
repository = "https://github.com/rust-lang-nursery/rustfmt"
readme = "README.md"
license = "Apache-2.0/MIT"
build = "build.rs"
categories = ["development-tools"]

[[bin]]
name = "cargo-fmt"
path = "src/cargo-fmt.rs"

[[bin]]
name = "git-rustfmt"
path = "src/git-rustfmt.rs"

[[bin]]
name = "rustfmt"
path = "src/rustfmt.rs"

[[bin]]
name = "rustfmt-format-diff"
path = "src/rustfmt-format-diff.rs"

[dev-dependencies]
lazy_static = "1.0.0"

[dependencies]
cargo_metadata = "0.4"
env_logger = "0.5"
getopts = "0.2"
log = "0.4"
regex = "0.2"
rustfmt-config = { path = "rustfmt-config" }
rustfmt-core = { path = "rustfmt-core" }
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
term = "0.4"
